pipeline {
    agent none
    stages {
        stage('Build') {
            agent any
            when {
                buildingTag()
            }
            steps {
                script {
                    println(TAG_NAME)
                    response = httpRequest \
                        httpMode: 'POST', \
                        url: 'https://api.github.com//repos/AlexVeprev/github_ci_workshop_2022/releases', \
                        authentication: "token_github_releases", \
                        requestBody: "{\"tag_name\":\"${TAG_NAME}\",\"name\":\"${TAG_NAME}\"}"
                    println('Status: '+response.status)
                    println('Response: '+response.content)
                    def parsed_response = readJSON text: response.content
                    println('Parsed ID: '+parsed_response.id)
                }
            }
        }
    }
}
