pipeline {
    agent none
    stages {
        stage('Build') {
            agent {
                dockerfile {
                    filename 'jenkins/Dockerfile.builder'
                }
            }
            steps {
                sh '''
                cmake -B build -S .
                cd build
                make VERBOSE=1
                ctest --output-on-failure
                cpack -G DEB
                '''
                stash includes: 'build/intsum-*-Linux.deb', name: 'linux_build'
            }
        }
        stage('Test matrix') {
            matrix {
                failFast true
                axes {
                   axis {
                       name 'OS'
                       values 'ub18', 'ub20', 'ub22', 'deb'
                   }
                }
                agent {
                    dockerfile {
                        filename "jenkins/Dockerfile.tester_${OS}"
                    }
                }
                stages {
                    // This stage is needed just to display OS in UI
                    stage('Axis') {
                        agent none
                        steps {
                            script {
                                stage("${OS}") {
                                    print "${OS}"
                                }
                            }
                        }
                    }

                    stage('Test') {
                        steps {
                            unstash 'linux_build'
                            sh 'sudo apt install -y ./build/intsum-*-Linux.deb'
                            sh 'cat /etc/*release'
                            sh 'jenkins/scripts/test.sh'
                        }
                    }
                }
            }
        }
    }
}
