pipeline {
    agent none
    stages {
        stage('Build') {
            agent {
                dockerfile {
                    filename 'jenkins/Dockerfile.builder'
                }
            }
            steps {
                sh '''
                cmake -B build -S .
                cd build
                make VERBOSE=1
                ctest --output-on-failure
                cpack -G DEB
                '''
                stash includes: 'build/intsum-*-Linux.deb', name: 'linux_build'
            }
        }
        stage('Test') {
            matrix {
                axes {
                   axis {
                       name 'OS'
                       values 'ub18', 'un20', 'ub22'
                   }
                }
                agent {
                    dockerfile {
                        filename "jenkins/Dockerfile.tester_${OS}"
                    }
                }
                stages {
                    stage("Test ${OS}") {
                        steps {
                            unstash 'linux_build'
                            sh 'sudo apt install -y ./build/intsum-*-Linux.deb'
                            sh 'jenkins/scripts/test.sh'
                        }
                    }
                }
            }
        }
    }
}
